variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN $SONAR_ARGS"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - package
  
code_quality_sonar:
  stage: test
  image: jakov/buildbox:jdk8
  variables:
  script:
    - mvn $MAVEN_CLI_OPTS clean verify sonar:sonar
